# Re-export public API from query modules
# Pure atomic database queries only - no business logic or orchestration

from app.assets.database.queries.asset import (
    asset_exists_by_hash,
    bulk_insert_assets,
    get_asset_by_hash,
    upsert_asset,
)
from app.assets.database.queries.asset_info import (
    asset_info_exists_for_asset_id,
    bulk_insert_asset_infos_ignore_conflicts,
    delete_asset_info_by_id,
    fetch_asset_info_and_asset,
    fetch_asset_info_asset_and_tags,
    get_asset_info_by_id,
    get_asset_info_ids_by_ids,
    get_or_create_asset_info,
    insert_asset_info,
    list_asset_infos_page,
    set_asset_info_metadata,
    set_asset_info_preview,
    update_asset_info_access_time,
    update_asset_info_name,
    update_asset_info_timestamps,
    update_asset_info_updated_at,
)
from app.assets.database.queries.cache_state import (
    CacheStateRow,
    bulk_insert_cache_states_ignore_conflicts,
    bulk_set_needs_verify,
    delete_assets_by_ids,
    delete_cache_states_by_ids,
    delete_cache_states_outside_prefixes,
    delete_orphaned_seed_asset,
    get_cache_states_by_paths_and_asset_ids,
    get_cache_states_for_prefixes,
    get_orphaned_seed_asset_ids,
    list_cache_states_by_asset_id,
    upsert_cache_state,
)
from app.assets.database.queries.tags import (
    add_missing_tag_for_asset_id,
    add_tags_to_asset_info,
    bulk_insert_tags_and_meta,
    ensure_tags_exist,
    get_asset_tags,
    list_tags_with_usage,
    remove_missing_tag_for_asset_id,
    remove_tags_from_asset_info,
    set_asset_info_tags,
)

__all__ = [
    # asset.py
    "asset_exists_by_hash",
    "get_asset_by_hash",
    "upsert_asset",
    "bulk_insert_assets",
    # asset_info.py
    "asset_info_exists_for_asset_id",
    "get_asset_info_by_id",
    "insert_asset_info",
    "get_or_create_asset_info",
    "update_asset_info_timestamps",
    "list_asset_infos_page",
    "fetch_asset_info_asset_and_tags",
    "fetch_asset_info_and_asset",
    "update_asset_info_access_time",
    "update_asset_info_name",
    "update_asset_info_updated_at",
    "set_asset_info_metadata",
    "delete_asset_info_by_id",
    "set_asset_info_preview",
    "bulk_insert_asset_infos_ignore_conflicts",
    "get_asset_info_ids_by_ids",
    # cache_state.py
    "CacheStateRow",
    "list_cache_states_by_asset_id",
    "upsert_cache_state",
    "delete_cache_states_outside_prefixes",
    "get_orphaned_seed_asset_ids",
    "delete_assets_by_ids",
    "get_cache_states_for_prefixes",
    "bulk_set_needs_verify",
    "delete_cache_states_by_ids",
    "delete_orphaned_seed_asset",
    "bulk_insert_cache_states_ignore_conflicts",
    "get_cache_states_by_paths_and_asset_ids",
    # tags.py
    "ensure_tags_exist",
    "get_asset_tags",
    "set_asset_info_tags",
    "add_tags_to_asset_info",
    "remove_tags_from_asset_info",
    "add_missing_tag_for_asset_id",
    "remove_missing_tag_for_asset_id",
    "list_tags_with_usage",
    "bulk_insert_tags_and_meta",
]
